stages:
  - deploy

deploy-job:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_BRANCH == "dev"
  tags:
    - dev
  script:
    - cd /srv/projects-docker/<PROJECT_NAME_DEV> && git pull && make build-development && make stop-development && make start-development

deploy-prod-job:
  stage: deploy
  tags:
    - prod
  only:
    - main
  when: manual
  script:
    - cd /srv/projects-docker/<PROJECT_NAME_PROD>
    - git pull
    - make build-production
    - make stop-production
    - make start-production
